"""Generate hatflow/_kernel.py (the unrolled LBM kernel). Run: python tools/gen_kernel.py"""
C=[[0,0,0],[1,0,0],[-1,0,0],[0,1,0],[0,-1,0],[0,0,1],[0,0,-1],[1,1,0],[-1,-1,0],[1,-1,0],[-1,1,0],[1,0,1],[-1,0,-1],[1,0,-1],[-1,0,1],[0,1,1],[0,-1,-1],[0,1,-1],[0,-1,1]]
W=[1/3]+[1/18]*6+[1/36]*12
OPP=[0,2,1,4,3,6,5,8,7,10,9,12,11,14,13,16,15,18,17]
def lin(coefs, names):
    t=[]
    for c,n in zip(coefs,names):
        if c==1: t.append(f"+{n}")
        elif c==-1: t.append(f"-{n}")
    return "".join(t) or "0.0"
def gen():
    L=[]
    a=L.append
    a("def _step(f, fn, flags, ufan, tau0, cs2, rho_out, u_out, nx, ny, nz, accumulate, u_sum, u2_sum):")
    a("    smag = 18.0 * math.sqrt(2.0) * cs2")
    a("    nyz = ny * nz")
    for q,(x,y,z) in enumerate(C):
        a(f"    o{q} = {x}*nyz + {y}*nz + {z}")
    a("    for i in prange(1, nx - 1):")
    a("        for j in range(1, ny - 1):")
    a("            base = i * nyz + j * nz")
    a("            for k in range(1, nz - 1):")
    a("                c = base + k")
    a("                fl = flags[c]")
    a("                if fl == 1 or fl == 3:")
    a("                    continue")
    for q in range(19):
        a(f"                s = c - o{q}")
        a(f"                g{q} = f[{OPP[q]}, c] if flags[s] == 1 else f[{q}, s]")
    a("                rho = " + "+".join(f"g{q}" for q in range(19)))
    for d,nm in enumerate("xyz"):
        a(f"                m{nm} = " + lin([C[q][d] for q in range(19)],[f"g{q}" for q in range(19)]))
    a("                if fl == 2:")
    a("                    ux = ufan[0, c]; uy = ufan[1, c]; uz = ufan[2, c]")
    a("                else:")
    a("                    ir = 1.0 / rho; ux = mx * ir; uy = my * ir; uz = mz * ir")
    a("                usq = 1.5 * (ux * ux + uy * uy + uz * uz)")
    for q in range(19):
        cu=lin([C[q][0],C[q][1],C[q][2]],["ux","uy","uz"])
        if cu=="0.0":
            a(f"                e{q} = {W[q]!r} * rho * (1.0 - usq)")
        else:
            a(f"                cu = 3.0 * ({cu})")
            a(f"                e{q} = {W[q]!r} * rho * (1.0 + cu + 0.5 * cu * cu - usq)")
    a("                if fl == 2:")
    for q in range(19):
        a(f"                    fn[{q}, c] = e{q}")
    a("                else:")
    for q in range(1,19):
        a(f"                    d{q} = g{q} - e{q}")
    pairs={"xx":(0,0),"yy":(1,1),"zz":(2,2),"xy":(0,1),"xz":(0,2),"yz":(1,2)}
    for nm,(p1,p2) in pairs.items():
        terms=[]
        for q in range(1,19):
            v=C[q][p1]*C[q][p2]
            if v==1: terms.append(f"+d{q}")
            elif v==-1: terms.append(f"-d{q}")
        a(f"                    p{nm} = " + ("".join(terms) or "0.0"))
    a("                    pn = math.sqrt(pxx * pxx + pyy * pyy + pzz * pzz + 2.0 * (pxy * pxy + pxz * pxz + pyz * pyz))")
    a("                    om = 2.0 / (tau0 + math.sqrt(tau0 * tau0 + smag * pn / rho))")
    for q in range(19):
        a(f"                    fn[{q}, c] = g{q} + om * (e{q} - g{q})")
    a("                rho_out[c] = rho")
    a("                u_out[0, c] = ux; u_out[1, c] = uy; u_out[2, c] = uz")
    a("                if accumulate:")
    a("                    u_sum[0, c] += ux; u_sum[1, c] += uy; u_sum[2, c] += uz")
    a("                    u2_sum[c] += ux * ux + uy * uy + uz * uz")
    return "\n".join(L)

HEADER = '''"""Fused stream + collide D3Q19 kernel, fully unrolled so numba keeps the
19 populations in registers (~2x faster than a looped kernel).

GENERATED by tools/gen_kernel.py -- edit the generator, not this file.
Arrays are flattened: f is (19, N), flags is (N,), ufan/u_out are (3, N).
Cell flags: 0 fluid, 1 solid (bounce-back), 2 fan (velocity forced), 3 boundary (skipped).
"""
import math

from numba import njit, prange


@njit(parallel=True, fastmath=True, cache=True)
'''

if __name__ == "__main__":
    import pathlib
    out = pathlib.Path(__file__).resolve().parents[1] / "hatflow" / "_kernel.py"
    out.write_text(HEADER + gen() + "\n")
    print("wrote", out)
