"""Fused stream + collide D3Q19 kernel, fully unrolled so numba keeps the
19 populations in registers (~2x faster than a looped kernel).

GENERATED by tools/gen_kernel.py -- edit the generator, not this file.
Arrays are flattened: f is (19, N), flags is (N,), ufan/u_out are (3, N).
Cell flags: 0 fluid, 1 solid (bounce-back), 2 fan (velocity forced), 3 boundary (skipped).
"""
import math

from numba import njit, prange


@njit(parallel=True, fastmath=True, cache=True)
def _step(f, fn, flags, ufan, tau0, cs2, rho_out, u_out, nx, ny, nz, accumulate, u_sum, u2_sum):
    smag = 18.0 * math.sqrt(2.0) * cs2
    nyz = ny * nz
    o0 = 0*nyz + 0*nz + 0
    o1 = 1*nyz + 0*nz + 0
    o2 = -1*nyz + 0*nz + 0
    o3 = 0*nyz + 1*nz + 0
    o4 = 0*nyz + -1*nz + 0
    o5 = 0*nyz + 0*nz + 1
    o6 = 0*nyz + 0*nz + -1
    o7 = 1*nyz + 1*nz + 0
    o8 = -1*nyz + -1*nz + 0
    o9 = 1*nyz + -1*nz + 0
    o10 = -1*nyz + 1*nz + 0
    o11 = 1*nyz + 0*nz + 1
    o12 = -1*nyz + 0*nz + -1
    o13 = 1*nyz + 0*nz + -1
    o14 = -1*nyz + 0*nz + 1
    o15 = 0*nyz + 1*nz + 1
    o16 = 0*nyz + -1*nz + -1
    o17 = 0*nyz + 1*nz + -1
    o18 = 0*nyz + -1*nz + 1
    for i in prange(1, nx - 1):
        for j in range(1, ny - 1):
            base = i * nyz + j * nz
            for k in range(1, nz - 1):
                c = base + k
                fl = flags[c]
                if fl == 1 or fl == 3:
                    continue
                s = c - o0
                g0 = f[0, c] if flags[s] == 1 else f[0, s]
                s = c - o1
                g1 = f[2, c] if flags[s] == 1 else f[1, s]
                s = c - o2
                g2 = f[1, c] if flags[s] == 1 else f[2, s]
                s = c - o3
                g3 = f[4, c] if flags[s] == 1 else f[3, s]
                s = c - o4
                g4 = f[3, c] if flags[s] == 1 else f[4, s]
                s = c - o5
                g5 = f[6, c] if flags[s] == 1 else f[5, s]
                s = c - o6
                g6 = f[5, c] if flags[s] == 1 else f[6, s]
                s = c - o7
                g7 = f[8, c] if flags[s] == 1 else f[7, s]
                s = c - o8
                g8 = f[7, c] if flags[s] == 1 else f[8, s]
                s = c - o9
                g9 = f[10, c] if flags[s] == 1 else f[9, s]
                s = c - o10
                g10 = f[9, c] if flags[s] == 1 else f[10, s]
                s = c - o11
                g11 = f[12, c] if flags[s] == 1 else f[11, s]
                s = c - o12
                g12 = f[11, c] if flags[s] == 1 else f[12, s]
                s = c - o13
                g13 = f[14, c] if flags[s] == 1 else f[13, s]
                s = c - o14
                g14 = f[13, c] if flags[s] == 1 else f[14, s]
                s = c - o15
                g15 = f[16, c] if flags[s] == 1 else f[15, s]
                s = c - o16
                g16 = f[15, c] if flags[s] == 1 else f[16, s]
                s = c - o17
                g17 = f[18, c] if flags[s] == 1 else f[17, s]
                s = c - o18
                g18 = f[17, c] if flags[s] == 1 else f[18, s]
                rho = g0+g1+g2+g3+g4+g5+g6+g7+g8+g9+g10+g11+g12+g13+g14+g15+g16+g17+g18
                mx = +g1-g2+g7-g8+g9-g10+g11-g12+g13-g14
                my = +g3-g4+g7-g8-g9+g10+g15-g16+g17-g18
                mz = +g5-g6+g11-g12-g13+g14+g15-g16-g17+g18
                if fl == 2:
                    ux = ufan[0, c]; uy = ufan[1, c]; uz = ufan[2, c]
                else:
                    ir = 1.0 / rho; ux = mx * ir; uy = my * ir; uz = mz * ir
                usq = 1.5 * (ux * ux + uy * uy + uz * uz)
                e0 = 0.3333333333333333 * rho * (1.0 - usq)
                cu = 3.0 * (+ux)
                e1 = 0.05555555555555555 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (-ux)
                e2 = 0.05555555555555555 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (+uy)
                e3 = 0.05555555555555555 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (-uy)
                e4 = 0.05555555555555555 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (+uz)
                e5 = 0.05555555555555555 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (-uz)
                e6 = 0.05555555555555555 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (+ux+uy)
                e7 = 0.027777777777777776 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (-ux-uy)
                e8 = 0.027777777777777776 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (+ux-uy)
                e9 = 0.027777777777777776 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (-ux+uy)
                e10 = 0.027777777777777776 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (+ux+uz)
                e11 = 0.027777777777777776 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (-ux-uz)
                e12 = 0.027777777777777776 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (+ux-uz)
                e13 = 0.027777777777777776 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (-ux+uz)
                e14 = 0.027777777777777776 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (+uy+uz)
                e15 = 0.027777777777777776 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (-uy-uz)
                e16 = 0.027777777777777776 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (+uy-uz)
                e17 = 0.027777777777777776 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                cu = 3.0 * (-uy+uz)
                e18 = 0.027777777777777776 * rho * (1.0 + cu + 0.5 * cu * cu - usq)
                if fl == 2:
                    fn[0, c] = e0
                    fn[1, c] = e1
                    fn[2, c] = e2
                    fn[3, c] = e3
                    fn[4, c] = e4
                    fn[5, c] = e5
                    fn[6, c] = e6
                    fn[7, c] = e7
                    fn[8, c] = e8
                    fn[9, c] = e9
                    fn[10, c] = e10
                    fn[11, c] = e11
                    fn[12, c] = e12
                    fn[13, c] = e13
                    fn[14, c] = e14
                    fn[15, c] = e15
                    fn[16, c] = e16
                    fn[17, c] = e17
                    fn[18, c] = e18
                else:
                    d1 = g1 - e1
                    d2 = g2 - e2
                    d3 = g3 - e3
                    d4 = g4 - e4
                    d5 = g5 - e5
                    d6 = g6 - e6
                    d7 = g7 - e7
                    d8 = g8 - e8
                    d9 = g9 - e9
                    d10 = g10 - e10
                    d11 = g11 - e11
                    d12 = g12 - e12
                    d13 = g13 - e13
                    d14 = g14 - e14
                    d15 = g15 - e15
                    d16 = g16 - e16
                    d17 = g17 - e17
                    d18 = g18 - e18
                    pxx = +d1+d2+d7+d8+d9+d10+d11+d12+d13+d14
                    pyy = +d3+d4+d7+d8+d9+d10+d15+d16+d17+d18
                    pzz = +d5+d6+d11+d12+d13+d14+d15+d16+d17+d18
                    pxy = +d7+d8-d9-d10
                    pxz = +d11+d12-d13-d14
                    pyz = +d15+d16-d17-d18
                    pn = math.sqrt(pxx * pxx + pyy * pyy + pzz * pzz + 2.0 * (pxy * pxy + pxz * pxz + pyz * pyz))
                    om = 2.0 / (tau0 + math.sqrt(tau0 * tau0 + smag * pn / rho))
                    fn[0, c] = g0 + om * (e0 - g0)
                    fn[1, c] = g1 + om * (e1 - g1)
                    fn[2, c] = g2 + om * (e2 - g2)
                    fn[3, c] = g3 + om * (e3 - g3)
                    fn[4, c] = g4 + om * (e4 - g4)
                    fn[5, c] = g5 + om * (e5 - g5)
                    fn[6, c] = g6 + om * (e6 - g6)
                    fn[7, c] = g7 + om * (e7 - g7)
                    fn[8, c] = g8 + om * (e8 - g8)
                    fn[9, c] = g9 + om * (e9 - g9)
                    fn[10, c] = g10 + om * (e10 - g10)
                    fn[11, c] = g11 + om * (e11 - g11)
                    fn[12, c] = g12 + om * (e12 - g12)
                    fn[13, c] = g13 + om * (e13 - g13)
                    fn[14, c] = g14 + om * (e14 - g14)
                    fn[15, c] = g15 + om * (e15 - g15)
                    fn[16, c] = g16 + om * (e16 - g16)
                    fn[17, c] = g17 + om * (e17 - g17)
                    fn[18, c] = g18 + om * (e18 - g18)
                rho_out[c] = rho
                u_out[0, c] = ux; u_out[1, c] = uy; u_out[2, c] = uz
                if accumulate:
                    u_sum[0, c] += ux; u_sum[1, c] += uy; u_sum[2, c] += uz
                    u2_sum[c] += ux * ux + uy * uy + uz * uz
